### ISSUE TITLE
Indentation not quite right

### ISSUE THREAD

**Issue by mylesthedev** [gorriecoe/atom-silverstripe#1]
Indentation of .ss pages seem to behave a bit weird.

Fro example if I have the follow code the h2 will try to align itself with the div above rather than indent inwards. This happens when I start to type inside the h2.

``` html
<div class="row">
    <div class="large-12 columns">
    <h2>Hello World</h2>
    </div>
</div>
```

Where as it should obviously be:

``` html
<div class="row">
    <div class="large-12 columns">
        <h2>Hello World</h2>
    </div>
</div>
```

**Comment by gorriecoe** [comment]
Hey mate,
This should be fixed from v1.12.1 onward.
