### ISSUE TITLE
Please don't add $this->extend('updateCMSFields', $fields); in getCMSFields()

### ISSUE THREAD

**Issue by axllent** [gorriecoe/atom-silverstripe#13]
It is, as I learned a while back, very bad practice to add `$this->extend('updateCMSFields', $fields);` in any object/page extending the default SilverStripe ones (SiteTree, DataObject etc).

This causes a extended functions to run multiple times due to `$fields = parent::getCMSFields();`. You can read more about this [here](https://github.com/silverstripe/silverstripe-lumberjack/issues/78).

**Comment by gorriecoe** [comment]
Thanks @axllent,  I have added a updated thes snippets in https://github.com/gorriecoe/atom-silverstripe/commit/935ddd682806ecaf42dfa25a284f5e971e185652.  Tell me what you think as I have added getCMSFieldScafoldless which uses `$this->extend('updateCMSFields', $fields);`

**Comment by gorriecoe** [comment]
Snippet output

getCMSField
```
    /**
     * CMS Fields
     * @return FieldList
     */
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->
        return $fields;
    }
```

getCMSFieldScafoldless
```
use SilverStripe\Forms\FieldList;
use SilverStripe\Forms\Tab;
use SilverStripe\Forms\TabSet;

...

    /**
     * CMS Fields
     * @return FieldList
     */
    public function getCMSFields()
    {
        $fields = FieldList::create();
        $fields->push(
            TabSet::create(
                'Root',
                Tab::create('Main')
            )
        );
        $fields->
        $this->extend('updateCMSFields', $fields);
        return $fields;
    }
```

**Comment by axllent** [comment]
Thanks @gorriecoe, that looks like the best approach!

I cannot remember ever (personally) using a Scafoldless approach, though I have worked with it a few times on other projects. My only concern (which you can probably either answer or address) is that the auto-complete potentially selects the `getCMSFieldScafoldless` *before* the regular `getCMSFields` (ie: the default first). If you can ensure that `getCMSFieldScafoldless` isn't the first when typing `getcm` then cool! 

Looking forward to the update!

**Comment by gorriecoe** [comment]
Totally agree and I have made sure getCMSFields is default before getCMSFieldScafoldless.  I'll push out an update now.

**Comment by gorriecoe** [comment]
@axllent https://github.com/gorriecoe/atom-silverstripe/commit/0e3a389f1d8d1fe1598ec68d75fcbdf03d9884ff is now available.

**Comment by axllent** [comment]
Fantastic, thanks @gorriecoe - I can confirm the update works as advertised :+1:
