### ISSUE TITLE
Limit php snippets to .php files?

### ISSUE THREAD

**Issue by tylerkidd** [gorriecoe/atom-silverstripe#3]
It would be great to limit PHP snippets to .php files - so much interference with common html attributes.

**Comment by gorriecoe** [comment]
Could you please provide a detailed example?

**Comment by tylerkidd** [comment]
When writing basic html. At minimum, reorder so tag attributes would be above.

<img width="505" alt="screen shot 2016-11-09 at 10 15 20 am" src="https://cloud.githubusercontent.com/assets/1338983/20145372/88bcd7f8-a665-11e6-8769-aaa6987e081a.png">

**Comment by gorriecoe** [comment]
I can't replicate this issue.  What are the other packages you have installed?

**Comment by tylerkidd** [comment]
Thanks @gorriecoe ! I dug a little deeper and found that it's actually an issue with https://github.com/atom/autocomplete-plus and they seem to have quite the list of issues so my problem might already be there somewhere. Because I only noticed it while working in SilverStripe template files, I thought it was coming in from atom-silverstripe.
