### ISSUE TITLE
Variables in href styling issues

### ISSUE THREAD

**Issue by aaronballz** [gorriecoe/atom-silverstripe#4]
Styling Issue with href="" and using variables. Picture explains better:

![image](https://cloud.githubusercontent.com/assets/23535821/20414668/77c0b5e8-ad98-11e6-8f4a-57c6071d5342.png)

**Comment by MattyBalaam** [comment]
Interesting. I just noticed a similar issue on a different language, possibly an issue with whatever handles the highlighting in Atom? https://github.com/atom/language-java/issues/68

**Comment by MattyBalaam** [comment]
Aha, will be fixed in Atom 1.13: https://github.com/atom/atom/issues/13142

**Comment by aaronballz** [comment]
Oh, good spotting! I did try to find if it was an atom issue but obviously put in all the wrong keywords on google ;) I'll close this issue off now then.
