### ISSUE TITLE
Enabling atom-silverstripe seems to cause linter to fail

### ISSUE THREAD

**Issue by grgcnnr** [gorriecoe/atom-silverstripe#6]
Not sure how atom-silverstripe and linter would even interact but thought I'd drop this here incase others were having the same issue. 

Enabling this plugin causes linter-sass-lint to fail silently and give any scss file a clean bill of health.

/shrug

```
Platform: darwin
Atom Version: 1.16.0
Linter Version: 2.1.4
All Linter Providers: 
  - JSHint
  - sass-lint
  - JSCS
Matching Linter Providers: 
  - sass-lint
Disabled Linter Providers; 

Current File scopes: 
  - *
  - source.css.scss
  - meta.property-list.scss
```

**Comment by grgcnnr** [comment]
Update: after cleaning out all atom preferences and re-installing. It seems to be affecting linter or linter-ui in its entirety. 

A Fresh install of Atom runs sass-lint, jshint and jscsrc fine. 

All go quiet when atom-silverstripe is enabled.

**Comment by grgcnnr** [comment]
This seems to have something to do with adding the various version syntaxes commenting out line 35 of silverstripe.js disables ss syntax but also solves the issue.

```
    var grammar = editor.getGrammar();
    for (var i = 0; i < syntax.length; i++) {
        if (grammar.scopeName.search(syntax[i]) == -1) {
            // grammar.scopeName = grammar.scopeName +'.'+ syntax[i];  <- Linter will now fire up just fine
        }
    }
```

This plugin is way too epic for my tiny brain to grok, but I'll keep crashing around and see if I can narrow it down as I'm guessing its only me. /shrug

**Comment by Arcanemagus** [comment]
Just to provide a bit of background info: `linter` only activates providers if their scope matches, so messing around with the scope like that will definitely break anything that depends on the scope (and is generally a _really bad idea_ ™️). I don't have the context of the code here to know why this is being done, but as it breaks literally every other package that depends on recognizing the language of a file I'd highly suggest finding another way to accomplish whatever you are trying to do here @gorriecoe.

**Comment by grgcnnr** [comment]
Ok well Im gonna roll back to 2.x for now @gorriecoe, I wanna say thanks for this rad package I use it a LOT for SS dev. Can I put a bounty on this bug or something? Appreciate you're busy doing real work. Either way I owe you a 🍺 or 2 next time I'm down south.

**Comment by gorriecoe** [comment]
Hey @grgcnnr,  Sorry for the late fix.  I have been super busy lately.  Could you test the changes I have made before I publish it?

**Comment by grgcnnr** [comment]
No apologies required! Will do today.

**Comment by grgcnnr** [comment]
So far so good. I’ll run it today and see how i get on.

**Comment by grgcnnr** [comment]
@gorriecoe seems good to me

**Comment by gorriecoe** [comment]
Cool thanks for that.
