### ISSUE TITLE
Massive memory leak?

### ISSUE THREAD

**Issue by MattyBalaam** [gorriecoe/atom-silverstripe#7]
Using this package on both current and beta versions of Atom on a Windows 10 machine as soon as I enter a $ into a silverstripe .ss file the editor will freeze and the Atom process memory usage will rocket up. The only way to stop the whole machine from freezing is to quit the process in task manager.

**Comment by MattyBalaam** [comment]
If I change **ss-variable-open** regex to a different character than the dollar sign. e.g.

`    'match': '\\£(\\.?[a-zA-Z0-9]*(\\([a-zA-Z0-9\'\, ]*\\))*)*'
`

Then the new character causes the issue.

**Comment by MattyBalaam** [comment]
I've changed to `\$([^\s]+)` for now. I'm sure there is a reason it should be more complicated though.

**Comment by MattyBalaam** [comment]
I’m looking on a Mac now, and I cannot reproduce the problem with the original match.

I also did not get the problem on a Windows 7 machine (I have just switched my machine to a windows 10 box on different hardware)

**Comment by gorriecoe** [comment]
Hey @MattyBalaam,  Thanks for the find.  The reason for the complex regex is for variables that may contain strings.  For example `$somefunction('a string in here')`.  I have come across this a few times and tried to find a fix for it.  I'm not sure how to fix this.  So any help would be appreciated.

Cheers

**Comment by gorriecoe** [comment]
Hey @MattyBalaam,  I think I may have fixed this.  Can you test the latest version to confirm this?

Cheers
