### ISSUE TITLE
Only half the Snippets are working

### ISSUE THREAD

**Issue by pxwee5** [gorriecoe/atom-silverstripe#8]
Not a lot of snippets are working actually. 

I'm on SS3.5 and all the examples shown in the readme are not working. 

Am I missing something ?

Community Packages (18) 
├── atom-silverstripe@3.0.4
├── atom-ternjs@0.18.3
├── autocomplete-modules@1.6.10
├── busy-signal@1.4.1
├── git-time-machine@1.5.9
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── javascript-snippets@1.2.1
├── language-javascript-jsx@0.3.7
├── language-nunjucks@4.1.0
├── linter@2.1.4
├── linter-eslint@8.2.0
├── linter-stylelint@3.10.0
├── linter-ui-default@1.6.0
├── minimap@4.28.2
├── minimap-highlight-selected@4.6.1
├── react@0.16.2
└── split-diff@1.4.0

```
"require": {
			"php": ">=5.3.2",
			"silverstripe/cms": "3.5.2",
			"silverstripe/framework": "3.5.2",
			"tractorcow/silverstripe-dynamiccache": "^4.1.0",
			"jonom/focuspoint": "^2.2",
			"undefinedoffset/sortablegridfield": "^0.6.2",
			"dnadesign/silverstripe-elemental": "dev-master",
      "heyday/silverstripe-versioneddataobjects": "^2.0",
			"sheadawson/silverstripe-linkable": "^1.3",
			"silverstripe/selectupload": "1.0.5",
			"markguinn/silverstripe-email-helpers": "master",
				"silverstripe/googlesitemaps": "^1.6",
				"wilr/silverstripe-googlesitemaps": "1.6.0"

		},
```

**Comment by MrJamesEllis** [comment]
Hmm I'm getting this as well, a few releases back i'd type 'getC' and get an autocompleted method for getCMSFields with a skeleton for dealing with fields, in the recent releases, nothing.
Currently on latest atom-silverstripe
Happy to test and debug the issue if required.

**Comment by gorriecoe** [comment]
Hey @pxwee5  and @MrJamesEllis.  Sorry for the late fix,  I have been super busy.  I have made a bunch of changes.  Would you be able to test the changes before I publish them.

The easiest way to test is to uninstall the existing package from atom.  Download this repo.  `cd` to the downloaded folder and run `apm link` and `apm install`

Cheers

**Comment by gorriecoe** [comment]
hi @pxwee5 and @MrJamesEllis, I'm confident my latest changes have fixed this issue.   The changes allow all snippets if composer can't be found.  Feel free to reopen this if you still have an issue.

**Comment by MrJamesEllis** [comment]
Sorry, couldn't get to the manual install but just updated to 3.1.1, all looking good to me so far. Thanks!
