### ISSUE TITLE
[3.2.0] SilverStripe template snippet loop issue

### ISSUE THREAD

**Issue by leochenftw** [gorriecoe/atom-silverstripe#9]
when you type loop and call the snippet, it gives you 
```
<% if  %>

<% else %>

<% end_loop %>
```

**Comment by gorriecoe** [comment]
Hey @leochenftw,  I can't reproduce this issue.  Can you check if there is a bug icon the bottom right of atom?  If there is can you rebuild any packages that may be broken?  Otherwise can you list all the packages installed?  Cheers

**Comment by leochenftw** [comment]
Hi @gorriecoe 

Thanks for your reply. No, I don't see a bug icon at the bottom. But, I think I know why: that was from silverstripe-bundle.

Sorry about the false alarm!

Cheers
Leo

**Comment by gorriecoe** [comment]
All good cheers
